spring:
  application:
    name: ms-notifications
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    consumer:
      group-id: notifications-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.ordersystem.ms_notifications.domain.CustomerEvent
        spring.json.trusted.packages: com.ordersystem.ms_notifications.domain
        spring.json.use.type.headers: false

server:
  port: 8082
